liv = 100

print("Jeg ble invitert på å spise middag hos noen jeg ikke kjente, ingen kjente hverandre så vi begynte med å spørre om hverandres navn mens vi ventet på maten ved boret")
navn=input("Mitt navn er ")
print("Magen rumlet ")
print("Når skal vi få maten? sa en ")
navn=input ("")
print("shh jeg hører skritt")
print("vi alle satt stille å var nervøse")
print("en tv monitor slo seg på, og vi alle skvatt")
print("dere er alle samlet her for en grunn...")
navn=input("")
print("STILLE! sa personen på monitoren")
print("jeg har samlet dere her for en stor pengegevinst på 20 millioner kroner, MEN! bare den siste som står igjen får denne gevinsten")
print("nå har dere 2 valg, dra nå for å overleve eller å bli for å kunne vinne")
valg=input ("A: bli B: dra ")
if  valg=="A":
    print("du blir igjen og dere alle som er igjen, ble drept")
    print("kroppene deres blir ikke oppdaget på flere uker å da de ble oppdaget så besvimte politiet")
    print("de fant ut hvem som sto bak dette etter en lang stund med etterforskning")
    if liv -  100:
        print(" - 100 ")
        print("Game Over ")
        exit()
    print(" :( ")
if  valg=="B":
    print("du drar hjem og overlever")
    print("du ser på nyhetene flere uker senere at det har vært massemord dær du var..")
    print("altid vær forsiktig når det gjelder fremmede")
    print("tenk på de grufulle måtene folkene som ble igjen ble myrdret på")
    print("denne gangen var du heldig")
    if liv +  100:
        print(" + 100")
        print("You Win ")
        exit()
    print("✨")